### PR TITLE
debian & ubuntu: Update packages

### PR DESCRIPTION
**Pull request by travier**
See: https://github.com/toolbx-images/images/issues/5

### CODE REVIEW

**Comment by Jmennius** [comment]
But why?
This will only make images larger.
We should get updated images by pulling new base images.

**Comment by travier** [comment]
We're already pulling new base images. See the discussion in #5. I agree that this increases the image size.

**Comment by travier** [comment]
We could also consider moving to podman and squash all layers to make images as small as possible: https://docs.podman.io/en/latest/markdown/podman-build.1.html#squash-all

**Comment by Jmennius** [comment]
But why upgrade at all? I just don't think it is worth it.
It was conscious decision on my part to not update packages in general, when building.
Yes, there can be something like a month (actually an interesting question if there is any commitment for update frequency in upstream builds) lag behind what's in the package repos, but that is usually not that many packages and if user really wants - they can do it themselves.

**Comment by travier** [comment]
OK, I'll close this one then. Can you mark yourself as maintainer for those images?

**Pull request closed without merging**
