### PR TITLE
debian: add debian 12 "bookworm" release

### PR DESCRIPTION
**Pull request by pennbauman**
It's nearly identical to Debian 11 and has been working for me. Are there specific tests an image should be put through?

Fixes: https://github.com/toolbx-images/images/issues/86

### CODE REVIEW

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
Thanks!

**Review by travier — CHANGES_REQUESTED** [review]
Can you add it to the README and to the GitHub workflows? Thanks

**Comment by pennbauman** [comment]
It should be added to both now

**Comment by travier** [comment]
Thanks!

**Pull request merged**
