### PR TITLE
Add Gentoo images

### PR DESCRIPTION
**Pull request by cheese**
This PR creates two images based on upstream ones with tags `latest` and `systemd`.

### CODE REVIEW

**Comment by travier** [comment]
Mostly LGTM. I would prefer that we don't carry our own ebuilds here but if it's not in Gentoo then I don't know what the best option is. Would submitting it to Gentoo be an option? Sorry I'm not up-to-date on Gentoo policies.

**Comment by cheese** [comment]
> 

Or is that acceptable to not carry `flatpak-spawn` for now?

**Comment by travier** [comment]
> Or is that acceptable to not carry `flatpak-spawn` for now?

I'd say it's better to have flatpak-spawn in the image but that means that you will have to maintain it here.

**Comment by travier** [comment]
Well, this is taking more than 6 hours to complete, so this is probably better done in another place, maybe in the Gentoo infrastructure.

**Pull request closed without merging**
