### PR TITLE
feat: add wolfi-toolbox images

### PR DESCRIPTION
**Pull request by 89luca89**
Add wolfi based toolbox images

This one also allows instant-enter on distrobox (has some extra packages)

Tagging @castrojo for additional discussion/requests

### CODE REVIEW

**Comment by castrojo** [comment]
https://github.com/containers/toolbox/issues/1474

@travier Since we're here already, would you mind if we pushed a zst:chunked image to `latest-zstd`? 

This would be a great opportunity to test alongside and we can always remove it later. (We can do that in a separate PR). Thoughts?

**Review by travier — DISMISSED** [review]

**Comment by travier** [comment]
Thanks, looks great. Can you also update the README?

**Review by Foxboron — DISMISSED** [review]

**Comment by travier** [comment]
I've made https://github.com/toolbx-images/images/issues/128 for the zstd::chunked enhancement.

**Comment by 89luca89** [comment]
> Thanks, looks great. Can you also update the README?

done thanks :+1:

**Review by Foxboron — APPROVED** [review]

**Pull request merged**
